# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 00:23
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('okcupid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='weight',
            field=models.IntegerField(
                choices=[(1, 'Not at all important'), (10, 'A little important'), (50, 'Somewhat important'),
                         (100, 'Very important'), (250, 'Mandatory')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='matchevaluation',
            name='evaluated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='okcupid.UserProfile'),
        ),
        migrations.AddField(
            model_name='matchevaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='okcupid.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='matchevaluation',
            unique_together=set([('evaluator', 'evaluated')]),
        ),
    ]
