# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('okcupid', '0004_auto_20170519_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientation',
            name='info',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
